// C.3 — Habits Audit: Cervical and Postural
// Source: Document 8 Part C section C.3. Verbatim member-facing prose for
// all seven cervical and postural habits.
//
// Personalisation: per-habit "Flagged for your profile" labels fire based on
// phase1_assessment columns. Per E23 design decision, four habits (H2, H3,
// H5, H6) are PERMANENTLY silent — no Phase 1 capture mechanism for their
// required flag columns. H1, H4, H7 fire when their underlying conditions
// are met.
//
// Paragraph shape: discriminated union to support H3's "Stomach sleeping" /
// "Side sleeping" / "Back sleeping" sub-headings within a single habit card.

import { SCORING_THRESHOLDS } from '@/content/scoring-thresholds'

// ── Content types ─────────────────────────────────────────────────────────────

// Paragraph entry — either body prose or a bold sub-heading.
// Only H3 currently uses subhead entries; other habits use exclusively 'p'.
export type C3Paragraph =
  | { kind: 'p'; text: string }
  | { kind: 'subhead'; text: string }

// Single cervical habit card — Doc 8 C.3 sections 1-7.
export type C3Habit = {
  id: string                  // 'H1'..'H7' — used as key in jsonb writes
  title: string
  paragraphs: C3Paragraph[]
  mechanismNote: string
  acknowledgeLabel: string
}

export type C3HabitsAuditCervical = {
  sectionLabel: string
  sectionTitle: string
  introduction: string
  habits: C3Habit[]
  sectionAcknowledgeLabel: string
}

// ── Content constant ──────────────────────────────────────────────────────────

export const C3_HABITS_AUDIT_CERVICAL: C3HabitsAuditCervical = {
  sectionLabel: 'Phase 2 \u2014 Lifestyle Foundations',
  sectionTitle: 'Habits Audit \u2014 Cervical and Postural',
  introduction:
    'Work through each habit below. For habits marked \u201cFlagged for ' +
    'your profile,\u201d your Phase 1 assessment identified this as an ' +
    'active maintaining factor in your specific case \u2014 it warrants ' +
    'particular attention.',
  sectionAcknowledgeLabel: 'I have read the cervical and postural habits section',
  habits: [
    // ── HABIT 1 — Phone and Reading Posture ──────────────────────────────
    {
      id: 'H1',
      title: '1. Phone and Reading Posture',
      paragraphs: [
        { kind: 'p', text:
          'The head weighs approximately 5kg in neutral position. For ' +
          'every inch it moves forward of the shoulders, the effective ' +
          'load on the cervical spine increases significantly \u2014 by ' +
          'some estimates reaching 20\u201330kg of effective load at a ' +
          '45-degree forward angle. Sustained forward head position is ' +
          'the single most common source of daily cervical loading for ' +
          'most people.' },
        { kind: 'p', text:
          'Phone use is the most frequent driver of this pattern. ' +
          'Looking down at a phone held at waist or chest height places ' +
          'the neck into sustained flexion for the duration of every ' +
          'scroll, message, or browsing session. Across a typical day ' +
          'this accumulates into hours of continuous cervical load.' },
        { kind: 'p', text:
          'The same applies to reading flat on a desk, working with ' +
          'physical documents laid horizontal, or reading a book held ' +
          'low. The position of the material determines the position of ' +
          'the head \u2014 material held low means the head angles down ' +
          'to meet it.' },
        { kind: 'p', text:
          'The fix in both cases is the same: raise the material to eye ' +
          'level where possible. Phone held higher, documents propped, ' +
          'books raised. The habit change feels unnatural initially ' +
          'because the low-position pattern is deeply ingrained \u2014 ' +
          'it normalises quickly.' },
      ],
      mechanismNote:
        'Forward head position during phone and reading use places the ' +
        'suboccipital muscles and upper cervical joints under sustained ' +
        'compressive and tensile load. The abnormal cervical afferent ' +
        'input generated by hours of daily forward flexion feeds ' +
        'directly into the same brainstem pathway that Phase 3 works to ' +
        'reduce. Addressing this habit reduces the daily mechanical ' +
        'input the protocol is working against.',
      acknowledgeLabel: 'I understand this habit and what I need to change',
    },

    // ── HABIT 2 — Screen Height ──────────────────────────────────────────
    {
      id: 'H2',
      title: '2. Screen Height',
      paragraphs: [
        { kind: 'p', text:
          'Screen height is the highest-leverage single workstation ' +
          'change available for reducing daily cervical load. A monitor ' +
          'or laptop screen positioned below eye level requires ' +
          'sustained cervical flexion throughout every desk session ' +
          '\u2014 often four to eight hours daily for people in ' +
          'sedentary occupations. Even a well-positioned spine cannot ' +
          'compensate for a screen that forces the head downward.' },
        { kind: 'p', text:
          'The correct screen position is: top of the screen at or ' +
          'just below eye level, screen at approximately arm\u2019s ' +
          'length. For laptop users without a separate keyboard this ' +
          'is not achievable with the laptop flat on a desk \u2014 the ' +
          'screen will always be too low. A laptop stand raising the ' +
          'screen to eye level combined with a separate keyboard is ' +
          'the solution. The combined cost is typically under \u00a330\u201340 ' +
          'and the cervical load reduction across a full working day ' +
          'is substantial.' },
        { kind: 'p', text:
          'If your Phase 1 assessment identified sustained desk load or ' +
          'low screen positioning as a confirmed maintaining factor, ' +
          'this is the single most impactful change available to you ' +
          'before Phase 3 begins.' },
      ],
      mechanismNote:
        'A screen positioned below eye level maintains the cervical ' +
        'spine in sustained flexion during all desk work. Unlike phone ' +
        'use which is intermittent, desk work typically involves hours ' +
        'of continuous low-head positioning. The cumulative cervical ' +
        'load across a full working week represents a significant ' +
        'ongoing source of abnormal upper cervical afferent input.',
      acknowledgeLabel: 'I understand this habit and what I need to change',
    },

    // ── HABIT 3 — Sleep Position (with subheadings) ──────────────────────
    {
      id: 'H3',
      title: '3. Sleep Position',
      paragraphs: [
        { kind: 'p', text:
          'Sleep position is one of the highest-impact cervical habits ' +
          'because of duration \u2014 seven or eight hours in a ' +
          'maintained position produces more cumulative cervical load ' +
          'than most waking habits.' },
        { kind: 'subhead', text: 'Stomach sleeping' },
        { kind: 'p', text:
          'Lying face down requires the neck to be rotated fully to ' +
          'one side for the entire sleep duration \u2014 sustained ' +
          'end-range cervical rotation maintained for hours. For ' +
          'members with confirmed cervical driver involvement, ' +
          'stomach sleeping is the sleep habit that most directly ' +
          'counteracts the Phase 3 protocol. Position change for ' +
          'stomach sleepers is flagged as a priority \u2014 not ' +
          'something to address gradually but something worth changing ' +
          'immediately.' },
        { kind: 'p', text:
          'Transitioning away from stomach sleeping is uncomfortable ' +
          'initially because it is a deeply habitual position. Side ' +
          'sleeping or back sleeping are both acceptable alternatives. ' +
          'A pillow between the knees can help with the transition to ' +
          'side sleeping by making it feel more stable.' },
        { kind: 'subhead', text: 'Side sleeping' },
        { kind: 'p', text:
          'Side sleeping is generally acceptable but pillow height ' +
          'matters. A pillow that is too flat allows the head to drop ' +
          'toward the mattress, placing the cervical spine into ' +
          'lateral flexion. A pillow that is too thick pushes the head ' +
          'upward into lateral flexion in the other direction. The ' +
          'goal is neutral cervical alignment \u2014 ear directly ' +
          'above the shoulder when lying on the side. Most standard ' +
          'pillows are adequate for average shoulder width; broader ' +
          'shoulders typically need a thicker pillow.' },
        { kind: 'subhead', text: 'Back sleeping' },
        { kind: 'p', text:
          'Back sleeping requires lower support \u2014 a thinner ' +
          'pillow or a contoured cervical pillow that supports the ' +
          'natural cervical curve without pushing the head forward ' +
          'into flexion.' },
      ],
      mechanismNote:
        'Sustained cervical rotation during stomach sleeping maintains ' +
        'end-range joint load and suboccipital muscle tension through ' +
        'the night. Hours of this position rebuilds the very tension ' +
        'the Phase 3 protocol releases during the day. Pillow height ' +
        'errors during side sleeping produce similar effects through ' +
        'sustained lateral flexion rather than rotation.',
      acknowledgeLabel: 'I understand this habit and what I need to change',
    },

    // ── HABIT 4 — Bag Carrying ───────────────────────────────────────────
    {
      id: 'H4',
      title: '4. Bag Carrying',
      paragraphs: [
        { kind: 'p', text:
          'Consistently carrying a bag on one shoulder elevates the ' +
          'carrying-side shoulder and reinforces the same asymmetric ' +
          'upper trapezius and levator scapulae tension identified in ' +
          'Phase 1. The body adapts to the load by chronically ' +
          'elevating the shoulder \u2014 a pattern that, over time, ' +
          'becomes the resting position even without the bag.' },
        { kind: 'p', text:
          'The fix is simple in principle: alternate shoulders ' +
          'regularly, or switch to a backpack that distributes load ' +
          'symmetrically. In practice, bag carrying habits are highly ' +
          'automatic \u2014 the bag goes on the same shoulder every ' +
          'time without conscious decision. The habit change requires ' +
          'a deliberate interruption until the alternating pattern ' +
          'becomes automatic.' },
        { kind: 'p', text:
          'For members with confirmed elevated shoulder asymmetry ' +
          'from Phase 1, the carrying side is worth checking against ' +
          'the elevated side. If they match \u2014 which is common ' +
          '\u2014 the bag carrying habit is a likely contributor to ' +
          'the asymmetric pattern the Phase 3 protocol addresses.' },
      ],
      mechanismNote:
        'Unilateral shoulder loading elevates the upper trapezius and ' +
        'levator scapulae on the carrying side, placing sustained load ' +
        'on the upper cervical transverse processes on that side. ' +
        'Chronic shoulder elevation maintains abnormal cervical ' +
        'afferent input and directly counteracts the cervical protocol ' +
        'work targeting the same muscles.',
      acknowledgeLabel: 'I understand this habit and what I need to change',
    },

    // ── HABIT 5 — Movement Breaks ────────────────────────────────────────
    {
      id: 'H5',
      title: '5. Movement Breaks',
      paragraphs: [
        { kind: 'p', text:
          'Sustained static posture is problematic regardless of how ' +
          'correct that posture is. The cervical spine and surrounding ' +
          'musculature are designed for movement \u2014 sustained ' +
          'loading in any fixed position, including a neutral one, ' +
          'produces progressive tension accumulation and reduced ' +
          'local circulation.' },
        { kind: 'p', text:
          'The intervention is simple: every 45 minutes, stand up and ' +
          'move. Not a stretch routine, not a structured break \u2014 ' +
          'stand up, move your shoulders through their range for 30 ' +
          'seconds, and sit back down. That is sufficient to ' +
          'interrupt the tension accumulation cycle. The movement ' +
          'itself matters more than its duration or complexity.' },
        { kind: 'p', text:
          'For people in sedentary occupations with four or more hours ' +
          'of daily desk time, this single habit change meaningfully ' +
          'reduces the cumulative cervical load across the working ' +
          'day. A phone reminder set to 45 minutes is the most ' +
          'reliable implementation \u2014 waiting until you feel stiff ' +
          'means the tension has already accumulated.' },
      ],
      mechanismNote:
        'Static posture reduces local muscular circulation and allows ' +
        'progressive tension accumulation in the cervical and ' +
        'suboccipital musculature. Brief movement every 45 minutes ' +
        'interrupts this cycle before significant tension builds. The ' +
        'effect is cumulative \u2014 consistent movement breaks across ' +
        'a full working day produce a substantially lower baseline ' +
        'cervical tension level than uninterrupted sustained sitting.',
      acknowledgeLabel: 'I understand this habit and what I need to change',
    },

    // ── HABIT 6 — Car Seat and Driving Posture ───────────────────────────
    {
      id: 'H6',
      title: '6. Car Seat and Driving Posture',
      paragraphs: [
        { kind: 'p', text:
          'Driving combines several cervical loading factors ' +
          'simultaneously: sustained static posture, forward head ' +
          'position relative to a poorly positioned headrest, and ' +
          '\u2014 for longer journeys \u2014 significant total ' +
          'duration. It is one of the contexts most commonly ' +
          'associated with tinnitus worsening reported by ' +
          'cervical-dominant members.' },
        { kind: 'p', text:
          'The headrest is the most frequently overlooked adjustment. ' +
          'Most car headrests sit too far back by default, which means ' +
          'the head sits forward of the headrest rather than ' +
          'supported by it \u2014 producing sustained forward head ' +
          'position for the entire drive. The headrest should be ' +
          'adjusted so it sits directly behind the head at rest, ' +
          'providing genuine support rather than functioning as a ' +
          'distant backstop.' },
        { kind: 'p', text:
          'Seat position also matters. A seat reclined too far back ' +
          'encourages the head to come forward to see the road. A ' +
          'more upright seat position \u2014 not rigidly vertical, ' +
          'but closer to 100\u2013110 degrees rather than heavily ' +
          'reclined \u2014 keeps the head naturally over the ' +
          'shoulders rather than in front of them.' },
        { kind: 'p', text:
          'For members who drive regularly as part of their occupation ' +
          '\u2014 or who identified driving as a context where ' +
          'tinnitus reliably worsens \u2014 these adjustments are ' +
          'worth treating as a priority.' },
      ],
      mechanismNote:
        'Sustained driving in forward head position loads the ' +
        'suboccipital muscles and upper cervical joints continuously ' +
        'for the journey duration. Long drives represent some of the ' +
        'highest single-session cervical load events in daily life. A ' +
        'correctly positioned headrest shifts the head into neutral ' +
        'alignment and substantially reduces this load.',
      acknowledgeLabel: 'I understand this habit and what I need to change',
    },

    // ── HABIT 7 — Asymmetric Sitting Habits ──────────────────────────────
    {
      id: 'H7',
      title: '7. Asymmetric Sitting Habits',
      paragraphs: [
        { kind: 'p', text:
          'How people sit when not consciously managing their posture ' +
          'reveals habitual asymmetric loading patterns. Common ' +
          'examples: sitting cross-legged with the same leg always on ' +
          'top, consistently tucking one foot under the opposite ' +
          'thigh, habitually leaning on one armrest, or sitting with ' +
          'weight shifted consistently onto one hip.' },
        { kind: 'p', text:
          'Each of these patterns drives pelvic asymmetry, which ' +
          'produces compensatory spinal loading up through the lumbar ' +
          'and thoracic spine and ultimately into the cervical ' +
          'region. The connection is indirect but real \u2014 the ' +
          'cervical spine compensates for what happens below it. ' +
          'Chronic asymmetric sitting habits contribute to the same ' +
          'postural asymmetry patterns identified in Phase 1 and ' +
          'addressed in Phase 4.' },
        { kind: 'p', text:
          'The habit change here is awareness and variation \u2014 ' +
          'noticing which asymmetric patterns are habitual and ' +
          'interrupting them. Symmetrical sitting does not need to be ' +
          'rigid or effortful; the goal is reducing consistent ' +
          'one-sided loading rather than achieving perfect posture.' },
      ],
      mechanismNote:
        'Pelvic asymmetry from habitual asymmetric sitting produces ' +
        'compensatory lateral spinal curvature that loads the cervical ' +
        'spine asymmetrically. Chronic cervical asymmetric loading ' +
        'maintains differential tension in the suboccipital and upper ' +
        'cervical musculature \u2014 directly relevant for members ' +
        'with lateralised cervical findings from Phase 1.',
      acknowledgeLabel: 'I understand this habit and what I need to change',
    },
  ],
}

// ── Personalisation helper ────────────────────────────────────────────────────

// Subset of phase1_assessment used by C.3 personalisation. Defined locally
// to avoid coupling to the full Phase1AssessmentRow type.
// cerv_normalised_score is passed separately as the universal gate.
export type C3AssessmentInput = {
  post_sustained_desk_load: boolean | null
  post_shoulder_asymmetry: boolean | null
}

// Returns true if the habit's "Flagged for your profile" label should fire
// for this member, false otherwise.
//
// Universal gate: cerv_normalised_score (0-100 percentage) must meet
// PROTOCOL_ASSIGNMENT_MINIMUM. Members with low cervical findings get no
// cervical-habit personalisation.
//
// E23 design decision: four habits (H2, H3, H5, H6) are PERMANENTLY silent.
// Doc 8 Phase 1 has no capture mechanism for the columns these habits
// would require (low_screen_positioning, stomach_sleeping,
// high_sustained_sitting_load, tinnitus_worse_driving). Habit content
// still renders for every member — only the supplementary label is omitted.
export function getC3HabitFlag(
  habitId: string,
  assessment: C3AssessmentInput | null,
  cervNormalisedScore: number | null
): boolean {
  if (
    cervNormalisedScore === null ||
    cervNormalisedScore < SCORING_THRESHOLDS.PROTOCOL_ASSIGNMENT_MINIMUM
  ) {
    return false
  }
  if (!assessment) return false

  switch (habitId) {
    // H1 — Phone/reading posture. Doc 8 system note: phone_posture OR
    // sustained_desk_load. phone_posture never captured (E23 expansion).
    // Falls back to post_sustained_desk_load only.
    case 'H1':
      return assessment.post_sustained_desk_load === true

    // H2 — Screen height. PERMANENT — no low_screen_positioning column per E23.
    case 'H2':
      return false

    // H3 — Sleep position. PERMANENT — no stomach_sleeping column per E21/E23.
    // Doc 8 also specifies a "priority flag" for this card when
    // stomach_sleeping is confirmed; that priority handling is also
    // PERMANENT silent absent the schema.
    case 'H3':
      return false

    // H4 — Bag carrying. Doc 8 system note: consistent_bag_carrying OR
    // elevated_shoulder. consistent_bag_carrying never captured (E23).
    // Falls back to post_shoulder_asymmetry only.
    case 'H4':
      return assessment.post_shoulder_asymmetry === true

    // H5 — Movement breaks. PERMANENT — no high_sustained_sitting_load column
    // per E23.
    case 'H5':
      return false

    // H6 — Driving posture. PERMANENT — no tinnitus_worse_driving column per E23.
    case 'H6':
      return false

    // H7 — Asymmetric sitting. Doc 8 system note: elevated_shoulder OR
    // asymmetric_sitting. asymmetric_sitting never captured (E23). Falls back
    // to post_shoulder_asymmetry only.
    case 'H7':
      return assessment.post_shoulder_asymmetry === true

    default:
      return false
  }
}
