// B.1 — Opening Section: The Common Mechanism
// Source: Document 8 Part B, section B.1. All members read this section before any
// module-specific content. No inputs. All prose verbatim from Doc 8.
//
// Spec note: the handoff lists "six sub-sections" but Doc 8 has exactly five.
// "Two Pathways, One Endpoint" spec says 3 paragraphs but Doc 8 has 4 — the fourth
// being "Both pathways lead to the same endpoint...". Both implemented per Doc 8.

export type ContentSubsection = {
  heading: string
  paragraphs: string[]
}

export type B1Opening = {
  sectionLabel: string
  sectionTitle: string
  subsections: ContentSubsection[]
  acknowledgeLabel: string
}

export const B1_OPENING: B1Opening = {
  sectionLabel: 'Phase 1: Identification',
  sectionTitle: 'The Common Mechanism',
  acknowledgeLabel: 'I have read this section',
  subsections: [
    {
      heading: 'Why Your Tinnitus Might Be Physical',
      paragraphs: [
        'Most people with tinnitus are told the same thing: it comes from the ears, there is no cure, and the goal is to learn to live with it. For many people that advice is incomplete. For some it is simply wrong.',
        'For a significant proportion of tinnitus sufferers, the sound is not primarily coming from the ears at all. It is being generated by the brain\u2019s sound processing system in response to physical signals from the jaw and neck. This is somatic tinnitus, and understanding why it happens is the foundation of everything in this framework.',
      ],
    },
    {
      heading: 'The Brain\u2019s Sound Processing Centre',
      paragraphs: [
        'Deep in the brainstem sits a structure called the dorsal cochlear nucleus. Its job is to process incoming sound information, taking raw auditory signals and beginning to make sense of them before passing them upward to the rest of the brain.',
        'What most people (including most audiologists) don\u2019t know is that the dorsal cochlear nucleus doesn\u2019t only receive input from the ears. It also receives input from the jaw and the upper neck.',
        'This isn\u2019t an accident of anatomy. It\u2019s thought to exist so the brain can distinguish between external sounds and the sounds your own body makes: chewing, swallowing, turning your head. The system is designed to suppress internally generated noise by tracking physical movement in the jaw and neck and adjusting auditory processing accordingly.',
        'When that system works correctly, you don\u2019t hear yourself chew. When it goes wrong (when the physical signals coming from the jaw or neck are abnormal or elevated), the dorsal cochlear nucleus becomes dysregulated. It starts generating activity that the brain interprets as sound even when no external sound exists.',
        'That is tinnitus.',
      ],
    },
    {
      heading: 'Two Pathways, One Endpoint',
      paragraphs: [
        'The physical signals that feed into the dorsal cochlear nucleus travel along two main routes.',
        'The first is through the jaw. The temporomandibular joint, the muscles that control jaw movement (particularly the masseter and pterygoid muscles) and the surrounding soft tissues all feed signals into a nerve called the trigeminal nerve. That nerve has a branch that runs directly in front of the ear and connects into the brainstem\u2019s auditory processing system. When the jaw is under sustained tension, when the joint is compressed or displaced, or when the masticatory muscles are chronically overactive, the signal travelling along this pathway is abnormal. The dorsal cochlear nucleus registers that abnormality and responds with elevated activity.',
        'The second pathway is through the upper neck. The joints and muscles of the upper cervical spine (particularly at the very top of the neck, just below the base of the skull) send a continuous stream of positional and movement information to the brain. This information travels through the upper cervical nerves and converges in the brainstem very close to where the jaw pathway feeds in. When the upper neck is chronically tense, when the joints are restricted, or when the deep stabilising muscles of the cervical spine are not functioning correctly, this pathway also produces abnormal input into the auditory processing system.',
        'Both pathways lead to the same endpoint: an overactive dorsal cochlear nucleus generating phantom sound.',
      ],
    },
    {
      heading: 'Why This Explains Your Experience',
      paragraphs: [
        'This mechanism explains several things about somatic tinnitus that the standard \u2018ear damage\u2019 model cannot.',
        'It explains why your tinnitus changes. If it were simply a product of cochlear damage, it would be constant. The fact that it fluctuates (louder on some days, quieter on others, changing with jaw movement or neck position) is direct evidence that physical inputs are driving it. Those inputs vary. The tinnitus varies with them.',
        'It explains why stress makes it worse. Psychological stress increases muscle tension throughout the body, specifically in the jaw and neck, where most people hold tension without realising it. More tension means more abnormal input into the auditory system.',
        'It explains why it often worsens after prolonged desk work, after chewing tough food, after sleeping in a poor position. Each of these activities loads the jaw or cervical structures. The tinnitus responds accordingly.',
        'It also explains why most standard treatments don\u2019t work for somatic tinnitus. Treatments aimed at the cochlea (the inner ear) are addressing the wrong structure. The problem is not in the ear. The problem is in the physical inputs feeding into the brain\u2019s sound processing system from the jaw and neck.',
      ],
    },
    {
      heading: 'What the Framework Does',
      paragraphs: [
        'This framework is built around a simple principle: identify which physical pathways are most active in your specific case, reduce the abnormal input those pathways are generating, and allow the dorsal cochlear nucleus to return to normal baseline activity.',
        'Phase 1 maps your specific pattern: which structures are involved, how significantly, and what maintaining factors are amplifying the signal. Phases 2 through 4 systematically address each one. Phase 5 is about consolidating the changes so they hold.',
        'There is no single protocol that works for everyone with somatic tinnitus because not everyone\u2019s driving pattern is the same. The personalisation in this framework is not a marketing feature; it is the mechanism by which the framework works. Accurate identification in Phase 1 is the foundation everything else is built on.',
        'Take your time with this phase. The thoroughness of your self-assessment directly determines the accuracy of what follows.',
      ],
    },
  ],
}
