// B.7 — Profile Output
// Source: Document 8 Part B, section B.7.
// This module renders the already-generated profile_paragraph from phase1_assessment
// plus the interactive protocol option selector (or acknowledge path for low-confidence
// and pure single-driver members), followed by the What Comes Next confirmation.
//
// The full profile_paragraph (Sections 1–5) is generated by generateAndSaveProfile
// and stored in the DB — this content file provides only the chrome, option cards,
// recommendation rationale, What Comes Next prose, and button labels.
//
// On confirm/acknowledge: writes protocol_option to framework_progress, advances
// current_phase to 2, and redirects to /framework/phase-2/session-1.
// (Both the write and phase advancement are handled by the M11c submit route.)
//
// Section 6 (option selector) omission rules per Doc 13 §4.5:
//   - Omitted for low-confidence members (edgeCaseFlags.lowConfidence !== null)
//   - Omitted for pure single-driver members (TMJ_DOMINANT or CERV_DOMINANT)
// These members see the acknowledge path instead.

import type {
  B7ProtocolOption,
  B7RecommendationRationale,
  B7ProfileOutput,
} from './types'

// ── Content ───────────────────────────────────────────────────────────────────

export const B7_PROFILE_OUTPUT: B7ProfileOutput = {
  id: 'B7',
  sessionNumber: 7,
  sectionLabel: 'Phase 1 \u2014 Identification',

  // sectionTitle: Doc 8 §B.7 does not specify a section title for the page heading.
  // 'Your Phase 1 Profile' chosen as the member-facing chrome above the output screen.
  // Documented decision.
  sectionTitle: 'Your Phase 1 Profile',

  // paragraphHeading: no Doc 8 heading specified for the position above the rendered
  // profile_paragraph. 'Your Profile' is a clean, neutral header that contextualises
  // the DB-rendered paragraph without repeating the section title. Documented decision.
  paragraphHeading: 'Your Profile',

  optionsHeading: 'Session Structure',

  // verbatim Doc 8 §B.7 Section 6 first line
  optionsIntro: 'Most members are assigned both protocols. How you run them together is a choice based on your available time and preference.',

  // Three options — exactly as defined in Doc 8 §B.7 Section 6 table, verbatim.
  options: [
    {
      value: 1,
      name: 'Sequential',
      description: 'Complete jaw release phase fully before introducing the cervical protocol. Lower daily time commitment, cleaner variable control.',
      recommendedFor: 'Limited available time or preference for focused approach.',
    },
    {
      value: 2,
      name: 'Parallel',
      description: 'Both protocols simultaneously from day one. Requires 40\u201350 minutes daily for combined release work.',
      recommendedFor: 'Confirmed dual primary driver profiles with sufficient time.',
    },
    {
      value: 3,
      name: 'Prioritised Parallel (default recommendation)',
      description: 'Full primary driver protocol daily plus reduced secondary component. Best balance of comprehensiveness and time for most members.',
      recommendedFor: 'Primary with strong secondary or primary with secondary profiles. Also suitable for dual drivers who prefer a lighter initial load.',
    },
  ],

  // Three recommendation rationale strings — verbatim Doc 8 §B.7 Section 6.
  // Rendered above the option cards for members who see Section 6.
  // Single driver and low-confidence members do not see this block.
  recommendations: [
    {
      profileTypePattern: 'dual',
      text: 'Both pathways are equally active \u2014 working them simultaneously from day one is the most efficient approach. Option 2 is recommended.',
    },
    {
      profileTypePattern: 'primary_strong_secondary',
      text: 'Your primary driver takes priority. Full primary protocol daily plus the two to three key secondary exercises gives comprehensive coverage without overcommitting time. Option 3 is recommended.',
    },
    {
      profileTypePattern: 'primary_with_secondary',
      text: 'One exercise from the secondary protocol alongside the full primary is the right balance for your profile. Option 3 is recommended.',
    },
  ],

  whatComesNextHeading: 'What Comes Next',

  // verbatim Doc 8 §B.7 Section 7 (two universal paragraphs).
  // A conditional block for members with confirmed high-impact maintaining factors
  // (stomach sleeping / sustained desk load) is rendered by the client component
  // from DB data — it is not static content and does not belong here.
  whatComesNextProse: [
    'Phase 2 begins now. It covers the daily habits, diet, and sleep foundations that need to be in place before your protocol work starts. Work through it at your own pace \u2014 Phase 3 unlocks when you\u2019ve confirmed the maintaining factors relevant to your profile are genuinely addressed. There is no time requirement.',
    'Phase 3 unlocks when Phase 2 is complete.',
  ],

  confirmButtonLabel: 'Confirm and continue to Phase 2',

  // acknowledgeIntro: Doc 8 §B.7 Section 6 specifies omission for single-driver and
  // low-confidence members but does not provide replacement copy for the no-option path.
  // Text below authored to contextualise why no selector appears. Documented decision.
  acknowledgeIntro: 'Your protocol assignment is set. No session structure choice needed for your profile.',

  acknowledgeButtonLabel: 'Continue to Phase 2',
}
